services:
  notes2latex:
    image: ghcr.io/advaypakhale/notes2latex:latest
    ports:
      - "8000:8000"
    env_file:
      - path: .env
        required: false
    volumes:
      - notes2latex-data:/app/data

volumes:
  notes2latex-data:
